//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package mx.isban.cifrascontrol.webservice.reproceso;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cancelacionDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cancelacionDTO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="aplicativo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fechaCancelacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="folioSAT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idCancelacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="importeComisInter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="importeIva" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="importeRetencion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numeroCuenta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="periodo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cancelacionDTO", propOrder = {
    "aplicativo",
    "fechaCancelacion",
    "folioSAT",
    "idCancelacion",
    "importeComisInter",
    "importeIva",
    "importeRetencion",
    "numeroCuenta",
    "periodo"
})
public class CancelacionDTO {

    protected String aplicativo;
    protected String fechaCancelacion;
    protected String folioSAT;
    protected String idCancelacion;
    protected String importeComisInter;
    protected String importeIva;
    protected String importeRetencion;
    protected String numeroCuenta;
    protected String periodo;

    /**
     * Gets the value of the aplicativo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAplicativo() {
        return aplicativo;
    }

    /**
     * Sets the value of the aplicativo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAplicativo(String value) {
        this.aplicativo = value;
    }

    /**
     * Gets the value of the fechaCancelacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaCancelacion() {
        return fechaCancelacion;
    }

    /**
     * Sets the value of the fechaCancelacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaCancelacion(String value) {
        this.fechaCancelacion = value;
    }

    /**
     * Gets the value of the folioSAT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolioSAT() {
        return folioSAT;
    }

    /**
     * Sets the value of the folioSAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolioSAT(String value) {
        this.folioSAT = value;
    }

    /**
     * Gets the value of the idCancelacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdCancelacion() {
        return idCancelacion;
    }

    /**
     * Sets the value of the idCancelacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdCancelacion(String value) {
        this.idCancelacion = value;
    }

    /**
     * Gets the value of the importeComisInter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporteComisInter() {
        return importeComisInter;
    }

    /**
     * Sets the value of the importeComisInter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporteComisInter(String value) {
        this.importeComisInter = value;
    }

    /**
     * Gets the value of the importeIva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporteIva() {
        return importeIva;
    }

    /**
     * Sets the value of the importeIva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporteIva(String value) {
        this.importeIva = value;
    }

    /**
     * Gets the value of the importeRetencion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporteRetencion() {
        return importeRetencion;
    }

    /**
     * Sets the value of the importeRetencion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporteRetencion(String value) {
        this.importeRetencion = value;
    }

    /**
     * Gets the value of the numeroCuenta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroCuenta() {
        return numeroCuenta;
    }

    /**
     * Sets the value of the numeroCuenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroCuenta(String value) {
        this.numeroCuenta = value;
    }

    /**
     * Gets the value of the periodo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodo() {
        return periodo;
    }

    /**
     * Sets the value of the periodo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodo(String value) {
        this.periodo = value;
    }

}
