//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package mx.isban.cifrascontrol.webservice.reproceso;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.isban.cifrascontrol.webservice.reproceso package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReprocesoException_QNAME = new QName("http://sei.reproceso.modulointegrador.isban.mx/", "ReprocesoException");
    private final static QName _ConsultarReprocesos_QNAME = new QName("http://sei.reproceso.modulointegrador.isban.mx/", "consultarReprocesos");
    private final static QName _SolicitarReproceso_QNAME = new QName("http://sei.reproceso.modulointegrador.isban.mx/", "solicitarReproceso");
    private final static QName _ConsultarReprocesosResponse_QNAME = new QName("http://sei.reproceso.modulointegrador.isban.mx/", "consultarReprocesosResponse");
    private final static QName _SolicitarReprocesoResponse_QNAME = new QName("http://sei.reproceso.modulointegrador.isban.mx/", "solicitarReprocesoResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.isban.cifrascontrol.webservice.reproceso
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SolicitarReproceso }
     * 
     */
    public SolicitarReproceso createSolicitarReproceso() {
        return new SolicitarReproceso();
    }

    /**
     * Create an instance of {@link SolicitarReprocesoResponse }
     * 
     */
    public SolicitarReprocesoResponse createSolicitarReprocesoResponse() {
        return new SolicitarReprocesoResponse();
    }

    /**
     * Create an instance of {@link ReprocesoException }
     * 
     */
    public ReprocesoException createReprocesoException() {
        return new ReprocesoException();
    }

    /**
     * Create an instance of {@link ConsultarReprocesos }
     * 
     */
    public ConsultarReprocesos createConsultarReprocesos() {
        return new ConsultarReprocesos();
    }

    /**
     * Create an instance of {@link ConsultarReprocesosResponse }
     * 
     */
    public ConsultarReprocesosResponse createConsultarReprocesosResponse() {
        return new ConsultarReprocesosResponse();
    }

    /**
     * Create an instance of {@link ReprocesoDTO }
     * 
     */
    public ReprocesoDTO createReprocesoDTO() {
        return new ReprocesoDTO();
    }

    /**
     * Create an instance of {@link SolicitudReprocesoDTO }
     * 
     */
    public SolicitudReprocesoDTO createSolicitudReprocesoDTO() {
        return new SolicitudReprocesoDTO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReprocesoException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sei.reproceso.modulointegrador.isban.mx/", name = "ReprocesoException")
    public JAXBElement<ReprocesoException> createReprocesoException(ReprocesoException value) {
        return new JAXBElement<ReprocesoException>(_ReprocesoException_QNAME, ReprocesoException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarReprocesos }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sei.reproceso.modulointegrador.isban.mx/", name = "consultarReprocesos")
    public JAXBElement<ConsultarReprocesos> createConsultarReprocesos(ConsultarReprocesos value) {
        return new JAXBElement<ConsultarReprocesos>(_ConsultarReprocesos_QNAME, ConsultarReprocesos.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SolicitarReproceso }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sei.reproceso.modulointegrador.isban.mx/", name = "solicitarReproceso")
    public JAXBElement<SolicitarReproceso> createSolicitarReproceso(SolicitarReproceso value) {
        return new JAXBElement<SolicitarReproceso>(_SolicitarReproceso_QNAME, SolicitarReproceso.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarReprocesosResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sei.reproceso.modulointegrador.isban.mx/", name = "consultarReprocesosResponse")
    public JAXBElement<ConsultarReprocesosResponse> createConsultarReprocesosResponse(ConsultarReprocesosResponse value) {
        return new JAXBElement<ConsultarReprocesosResponse>(_ConsultarReprocesosResponse_QNAME, ConsultarReprocesosResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SolicitarReprocesoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sei.reproceso.modulointegrador.isban.mx/", name = "solicitarReprocesoResponse")
    public JAXBElement<SolicitarReprocesoResponse> createSolicitarReprocesoResponse(SolicitarReprocesoResponse value) {
        return new JAXBElement<SolicitarReprocesoResponse>(_SolicitarReprocesoResponse_QNAME, SolicitarReprocesoResponse.class, null, value);
    }

}
