//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package mx.isban.cifrascontrol.webservice.reproceso;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "Reproceso", targetNamespace = "http://sei.reproceso.modulointegrador.isban.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Reproceso {


    /**
     * 
     * @param solicitudReproceso
     * @return
     *     returns int
     * @throws ReprocesoException_Exception
     */
    @WebMethod
    @WebResult(name = "filasAfectadas", targetNamespace = "")
    @RequestWrapper(localName = "solicitarReproceso", targetNamespace = "http://sei.reproceso.modulointegrador.isban.mx/", className = "mx.isban.cifrascontrol.webservice.reproceso.SolicitarReproceso")
    @ResponseWrapper(localName = "solicitarReprocesoResponse", targetNamespace = "http://sei.reproceso.modulointegrador.isban.mx/", className = "mx.isban.cifrascontrol.webservice.reproceso.SolicitarReprocesoResponse")
    @Action(input = "http://sei.reproceso.modulointegrador.isban.mx/Reproceso/solicitarReprocesoRequest", output = "http://sei.reproceso.modulointegrador.isban.mx/Reproceso/solicitarReprocesoResponse", fault = {
        @FaultAction(className = ReprocesoException_Exception.class, value = "http://sei.reproceso.modulointegrador.isban.mx/Reproceso/solicitarReproceso/Fault/ReprocesoException")
    })
    public int solicitarReproceso(
        @WebParam(name = "SolicitudReproceso", targetNamespace = "")
        SolicitudReprocesoDTO solicitudReproceso)
        throws ReprocesoException_Exception
    ;

    /**
     * 
     * @param periodo
     * @return
     *     returns java.util.List<mx.isban.cifrascontrol.webservice.reproceso.ReprocesoDTO>
     * @throws ReprocesoException_Exception
     */
    @WebMethod
    @WebResult(name = "detalleReprocesos", targetNamespace = "")
    @RequestWrapper(localName = "consultarReprocesos", targetNamespace = "http://sei.reproceso.modulointegrador.isban.mx/", className = "mx.isban.cifrascontrol.webservice.reproceso.ConsultarReprocesos")
    @ResponseWrapper(localName = "consultarReprocesosResponse", targetNamespace = "http://sei.reproceso.modulointegrador.isban.mx/", className = "mx.isban.cifrascontrol.webservice.reproceso.ConsultarReprocesosResponse")
    @Action(input = "http://sei.reproceso.modulointegrador.isban.mx/Reproceso/consultarReprocesosRequest", output = "http://sei.reproceso.modulointegrador.isban.mx/Reproceso/consultarReprocesosResponse", fault = {
        @FaultAction(className = ReprocesoException_Exception.class, value = "http://sei.reproceso.modulointegrador.isban.mx/Reproceso/consultarReprocesos/Fault/ReprocesoException")
    })
    public List<ReprocesoDTO> consultarReprocesos(
        @WebParam(name = "periodo", targetNamespace = "")
        String periodo)
        throws ReprocesoException_Exception
    ;

}
