//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package mx.isban.cifrascontrol.webservice.reproceso;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ReprocesoService", targetNamespace = "http://sib.reproceso.modulointegrador.isban.mx/", wsdlLocation = "META-INF/wsdl/ReprocesoService.wsdl")
public class ReprocesoService
    extends Service
{

    private final static URL REPROCESOSERVICE_WSDL_LOCATION;
    private final static WebServiceException REPROCESOSERVICE_EXCEPTION;
    private final static QName REPROCESOSERVICE_QNAME = new QName("http://sib.reproceso.modulointegrador.isban.mx/", "ReprocesoService");

    static {
            REPROCESOSERVICE_WSDL_LOCATION = mx.isban.cifrascontrol.webservice.reproceso.ReprocesoService.class.getResource("/META-INF/wsdl/ReprocesoService.wsdl");
        WebServiceException e = null;
        if (REPROCESOSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/ReprocesoService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        REPROCESOSERVICE_EXCEPTION = e;
    }

    public ReprocesoService() {
        super(__getWsdlLocation(), REPROCESOSERVICE_QNAME);
    }

    public ReprocesoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REPROCESOSERVICE_QNAME, features);
    }

    public ReprocesoService(URL wsdlLocation) {
        super(wsdlLocation, REPROCESOSERVICE_QNAME);
    }

    public ReprocesoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REPROCESOSERVICE_QNAME, features);
    }

    public ReprocesoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReprocesoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Reproceso
     */
    @WebEndpoint(name = "ReprocesoImplPort")
    public Reproceso getReprocesoImplPort() {
        return super.getPort(new QName("http://sib.reproceso.modulointegrador.isban.mx/", "ReprocesoImplPort"), Reproceso.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Reproceso
     */
    @WebEndpoint(name = "ReprocesoImplPort")
    public Reproceso getReprocesoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sib.reproceso.modulointegrador.isban.mx/", "ReprocesoImplPort"), Reproceso.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REPROCESOSERVICE_EXCEPTION!= null) {
            throw REPROCESOSERVICE_EXCEPTION;
        }
        return REPROCESOSERVICE_WSDL_LOCATION;
    }

}
