//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package mx.isban.cifrascontrol.webservice.reproceso;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for solicitarReproceso complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="solicitarReproceso">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SolicitudReproceso" type="{http://sei.reproceso.modulointegrador.isban.mx/}solicitudReprocesoDTO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "solicitarReproceso", propOrder = {
    "solicitudReproceso"
})
public class SolicitarReproceso {

    @XmlElement(name = "SolicitudReproceso")
    protected SolicitudReprocesoDTO solicitudReproceso;

    /**
     * Gets the value of the solicitudReproceso property.
     * 
     * @return
     *     possible object is
     *     {@link SolicitudReprocesoDTO }
     *     
     */
    public SolicitudReprocesoDTO getSolicitudReproceso() {
        return solicitudReproceso;
    }

    /**
     * Sets the value of the solicitudReproceso property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolicitudReprocesoDTO }
     *     
     */
    public void setSolicitudReproceso(SolicitudReprocesoDTO value) {
        this.solicitudReproceso = value;
    }

}
