//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package mx.isban.cifrascontrol.webservice.cifrascontrol;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "CifrasControlService", targetNamespace = "http://sib.cifrascontrol.modulointegrador.isban.mx/", wsdlLocation = "META-INF/wsdl/CifrasControlService.wsdl")
public class CifrasControlService
    extends Service
{

    private final static URL CIFRASCONTROLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CIFRASCONTROLSERVICE_EXCEPTION;
    private final static QName CIFRASCONTROLSERVICE_QNAME = new QName("http://sib.cifrascontrol.modulointegrador.isban.mx/", "CifrasControlService");

    static {
            CIFRASCONTROLSERVICE_WSDL_LOCATION = mx.isban.cifrascontrol.webservice.cifrascontrol.CifrasControlService.class.getResource("/META-INF/wsdl/CifrasControlService.wsdl");
        WebServiceException e = null;
        if (CIFRASCONTROLSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/CifrasControlService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CIFRASCONTROLSERVICE_EXCEPTION = e;
    }

    public CifrasControlService() {
        super(__getWsdlLocation(), CIFRASCONTROLSERVICE_QNAME);
    }

    public CifrasControlService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CIFRASCONTROLSERVICE_QNAME);
    }

    public CifrasControlService(URL wsdlLocation) {
        super(wsdlLocation, CIFRASCONTROLSERVICE_QNAME);
    }

    public CifrasControlService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CIFRASCONTROLSERVICE_QNAME);
    }

    public CifrasControlService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CifrasControlService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns CifrasControl
     */
    @WebEndpoint(name = "CifrasControlImplPort")
    public CifrasControl getCifrasControlImplPort() {
        return super.getPort(new QName("http://sib.cifrascontrol.modulointegrador.isban.mx/", "CifrasControlImplPort"), CifrasControl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CifrasControl
     */
    @WebEndpoint(name = "CifrasControlImplPort")
    public CifrasControl getCifrasControlImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sib.cifrascontrol.modulointegrador.isban.mx/", "CifrasControlImplPort"), CifrasControl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CIFRASCONTROLSERVICE_EXCEPTION!= null) {
            throw CIFRASCONTROLSERVICE_EXCEPTION;
        }
        return CIFRASCONTROLSERVICE_WSDL_LOCATION;
    }

}
