//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package mx.isban.cifrascontrol.webservice.cifrascontrol;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cifrasControlDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cifrasControlDTO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="aplicativo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cantidadCuentas" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="comisionesIntereses" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cuentasConIncidencias" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cuentasConSello" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cuentasSinSello" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fase" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ivas" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="moneda" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="periodo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="retenciones" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tipoDocumento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cifrasControlDTO", propOrder = {
    "aplicativo",
    "cantidadCuentas",
    "comisionesIntereses",
    "cuentasConIncidencias",
    "cuentasConSello",
    "cuentasSinSello",
    "fase",
    "id",
    "ivas",
    "moneda",
    "periodo",
    "retenciones",
    "status",
    "tipoDocumento"
})
public class CifrasControlDTO {

    protected String aplicativo;
    protected String cantidadCuentas;
    protected String comisionesIntereses;
    protected String cuentasConIncidencias;
    protected String cuentasConSello;
    protected String cuentasSinSello;
    protected String fase;
    protected String id;
    protected String ivas;
    protected String moneda;
    protected String periodo;
    protected String retenciones;
    protected String status;
    protected String tipoDocumento;

    /**
     * Gets the value of the aplicativo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAplicativo() {
        return aplicativo;
    }

    /**
     * Sets the value of the aplicativo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAplicativo(String value) {
        this.aplicativo = value;
    }

    /**
     * Gets the value of the cantidadCuentas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCantidadCuentas() {
        return cantidadCuentas;
    }

    /**
     * Sets the value of the cantidadCuentas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCantidadCuentas(String value) {
        this.cantidadCuentas = value;
    }

    /**
     * Gets the value of the comisionesIntereses property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComisionesIntereses() {
        return comisionesIntereses;
    }

    /**
     * Sets the value of the comisionesIntereses property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComisionesIntereses(String value) {
        this.comisionesIntereses = value;
    }

    /**
     * Gets the value of the cuentasConIncidencias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCuentasConIncidencias() {
        return cuentasConIncidencias;
    }

    /**
     * Sets the value of the cuentasConIncidencias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCuentasConIncidencias(String value) {
        this.cuentasConIncidencias = value;
    }

    /**
     * Gets the value of the cuentasConSello property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCuentasConSello() {
        return cuentasConSello;
    }

    /**
     * Sets the value of the cuentasConSello property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCuentasConSello(String value) {
        this.cuentasConSello = value;
    }

    /**
     * Gets the value of the cuentasSinSello property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCuentasSinSello() {
        return cuentasSinSello;
    }

    /**
     * Sets the value of the cuentasSinSello property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCuentasSinSello(String value) {
        this.cuentasSinSello = value;
    }

    /**
     * Gets the value of the fase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFase() {
        return fase;
    }

    /**
     * Sets the value of the fase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFase(String value) {
        this.fase = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the ivas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIvas() {
        return ivas;
    }

    /**
     * Sets the value of the ivas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIvas(String value) {
        this.ivas = value;
    }

    /**
     * Gets the value of the moneda property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoneda() {
        return moneda;
    }

    /**
     * Sets the value of the moneda property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoneda(String value) {
        this.moneda = value;
    }

    /**
     * Gets the value of the periodo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodo() {
        return periodo;
    }

    /**
     * Sets the value of the periodo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodo(String value) {
        this.periodo = value;
    }

    /**
     * Gets the value of the retenciones property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetenciones() {
        return retenciones;
    }

    /**
     * Sets the value of the retenciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetenciones(String value) {
        this.retenciones = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the tipoDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDocumento() {
        return tipoDocumento;
    }

    /**
     * Sets the value of the tipoDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoDocumento(String value) {
        this.tipoDocumento = value;
    }

}
