//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package mx.isban.cifrascontrol.webservice.cifrascontrol;

import javax.xml.ws.WebFault;

@WebFault(name = "CifrasControlException", targetNamespace = "http://sei.cifrascontrol.modulointegrador.isban.mx/")
public class CifrasControlException_Exception
    extends Exception
{

    /**
	 * Serial
	 */
	private static final long serialVersionUID = 7197593333324079722L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CifrasControlException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CifrasControlException_Exception(String message, CifrasControlException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public CifrasControlException_Exception(String message, CifrasControlException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: mx.isban.cifrascontrol.webservice.cifrascontrol.CifrasControlException
     */
    public CifrasControlException getFaultInfo() {
        return faultInfo;
    }

}
