//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package mx.isban.cifrascontrol.webservice.cifrascontrol;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for consultarIncidenciasCifrasControlResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="consultarIncidenciasCifrasControlResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="incidenciasCifrasControlList" type="{http://sei.cifrascontrol.modulointegrador.isban.mx/}detalleCifrasControlDTO" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consultarIncidenciasCifrasControlResponse", propOrder = {
    "incidenciasCifrasControlList"
})
public class ConsultarIncidenciasCifrasControlResponse {

    protected List<DetalleCifrasControlDTO> incidenciasCifrasControlList;

    /**
     * Gets the value of the incidenciasCifrasControlList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incidenciasCifrasControlList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncidenciasCifrasControlList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DetalleCifrasControlDTO }
     * 
     * 
     */
    public List<DetalleCifrasControlDTO> getIncidenciasCifrasControlList() {
        if (incidenciasCifrasControlList == null) {
            incidenciasCifrasControlList = new ArrayList<DetalleCifrasControlDTO>();
        }
        return this.incidenciasCifrasControlList;
    }

}
