//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package mx.isban.cifrascontrol.webservice.cifrascontrol;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for consultarCifrasControl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="consultarCifrasControl">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SolicitudCifrasControl" type="{http://sei.cifrascontrol.modulointegrador.isban.mx/}solicitudCifrasControlDTO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consultarCifrasControl", propOrder = {
    "solicitudCifrasControl"
})
public class ConsultarCifrasControl {

    @XmlElement(name = "SolicitudCifrasControl")
    protected SolicitudCifrasControlDTO solicitudCifrasControl;

    /**
     * Gets the value of the solicitudCifrasControl property.
     * 
     * @return
     *     possible object is
     *     {@link SolicitudCifrasControlDTO }
     *     
     */
    public SolicitudCifrasControlDTO getSolicitudCifrasControl() {
        return solicitudCifrasControl;
    }

    /**
     * Sets the value of the solicitudCifrasControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolicitudCifrasControlDTO }
     *     
     */
    public void setSolicitudCifrasControl(SolicitudCifrasControlDTO value) {
        this.solicitudCifrasControl = value;
    }

}
