//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package mx.isban.cifrascontrol.webservice.cifrascontrol;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for consultarDetalleCifrasControl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="consultarDetalleCifrasControl">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SolicitudDetalleCifrasControl" type="{http://sei.cifrascontrol.modulointegrador.isban.mx/}solicitudCifrasControlDTO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consultarDetalleCifrasControl", propOrder = {
    "solicitudDetalleCifrasControl"
})
public class ConsultarDetalleCifrasControl {

    @XmlElement(name = "SolicitudDetalleCifrasControl")
    protected SolicitudCifrasControlDTO solicitudDetalleCifrasControl;

    /**
     * Gets the value of the solicitudDetalleCifrasControl property.
     * 
     * @return
     *     possible object is
     *     {@link SolicitudCifrasControlDTO }
     *     
     */
    public SolicitudCifrasControlDTO getSolicitudDetalleCifrasControl() {
        return solicitudDetalleCifrasControl;
    }

    /**
     * Sets the value of the solicitudDetalleCifrasControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolicitudCifrasControlDTO }
     *     
     */
    public void setSolicitudDetalleCifrasControl(SolicitudCifrasControlDTO value) {
        this.solicitudDetalleCifrasControl = value;
    }

}
