//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package mx.isban.cifrascontrol.webservice.cifrascontrol;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.isban.cifrascontrol.webservice.cifrascontrol package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CifrasControlException_QNAME = new QName("http://sei.cifrascontrol.modulointegrador.isban.mx/", "CifrasControlException");
    private final static QName _ConsultarCifrasControlResponse_QNAME = new QName("http://sei.cifrascontrol.modulointegrador.isban.mx/", "consultarCifrasControlResponse");
    private final static QName _ConsultarFacturasCifrasControlResponse_QNAME = new QName("http://sei.cifrascontrol.modulointegrador.isban.mx/", "consultarFacturasCifrasControlResponse");
    private final static QName _ConsultarDetalleCifrasControlResponse_QNAME = new QName("http://sei.cifrascontrol.modulointegrador.isban.mx/", "consultarDetalleCifrasControlResponse");
    private final static QName _ConsultarCifrasControl_QNAME = new QName("http://sei.cifrascontrol.modulointegrador.isban.mx/", "consultarCifrasControl");
    private final static QName _ConsultarDetalleCifrasControl_QNAME = new QName("http://sei.cifrascontrol.modulointegrador.isban.mx/", "consultarDetalleCifrasControl");
    private final static QName _ConsultarFacturasCifrasControl_QNAME = new QName("http://sei.cifrascontrol.modulointegrador.isban.mx/", "consultarFacturasCifrasControl");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.isban.cifrascontrol.webservice.cifrascontrol
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsultarDetalleCifrasControlResponse }
     * 
     */
    public ConsultarDetalleCifrasControlResponse createConsultarDetalleCifrasControlResponse() {
        return new ConsultarDetalleCifrasControlResponse();
    }

    /**
     * Create an instance of {@link ConsultarFacturasCifrasControl }
     * 
     */
    public ConsultarFacturasCifrasControl createConsultarFacturasCifrasControl() {
        return new ConsultarFacturasCifrasControl();
    }

    /**
     * Create an instance of {@link ConsultarFacturasCifrasControlResponse }
     * 
     */
    public ConsultarFacturasCifrasControlResponse createConsultarFacturasCifrasControlResponse() {
        return new ConsultarFacturasCifrasControlResponse();
    }

    /**
     * Create an instance of {@link CifrasControlException }
     * 
     */
    public CifrasControlException createCifrasControlException() {
        return new CifrasControlException();
    }

    /**
     * Create an instance of {@link ConsultarCifrasControl }
     * 
     */
    public ConsultarCifrasControl createConsultarCifrasControl() {
        return new ConsultarCifrasControl();
    }

    /**
     * Create an instance of {@link ConsultarCifrasControlResponse }
     * 
     */
    public ConsultarCifrasControlResponse createConsultarCifrasControlResponse() {
        return new ConsultarCifrasControlResponse();
    }

    /**
     * Create an instance of {@link ConsultarDetalleCifrasControl }
     * 
     */
    public ConsultarDetalleCifrasControl createConsultarDetalleCifrasControl() {
        return new ConsultarDetalleCifrasControl();
    }

    /**
     * Create an instance of {@link CifrasControlDTO }
     * 
     */
    public CifrasControlDTO createCifrasControlDTO() {
        return new CifrasControlDTO();
    }

    /**
     * Create an instance of {@link FacturaDTO }
     * 
     */
    public FacturaDTO createFacturaDTO() {
        return new FacturaDTO();
    }

    /**
     * Create an instance of {@link SolicitudCifrasControlDTO }
     * 
     */
    public SolicitudCifrasControlDTO createSolicitudCifrasControlDTO() {
        return new SolicitudCifrasControlDTO();
    }

    /**
     * Create an instance of {@link SolicitudFacturaDTO }
     * 
     */
    public SolicitudFacturaDTO createSolicitudFacturaDTO() {
        return new SolicitudFacturaDTO();
    }

    /**
     * Create an instance of {@link DetalleCifrasControlDTO }
     * 
     */
    public DetalleCifrasControlDTO createDetalleCifrasControlDTO() {
        return new DetalleCifrasControlDTO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CifrasControlException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sei.cifrascontrol.modulointegrador.isban.mx/", name = "CifrasControlException")
    public JAXBElement<CifrasControlException> createCifrasControlException(CifrasControlException value) {
        return new JAXBElement<CifrasControlException>(_CifrasControlException_QNAME, CifrasControlException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarCifrasControlResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sei.cifrascontrol.modulointegrador.isban.mx/", name = "consultarCifrasControlResponse")
    public JAXBElement<ConsultarCifrasControlResponse> createConsultarCifrasControlResponse(ConsultarCifrasControlResponse value) {
        return new JAXBElement<ConsultarCifrasControlResponse>(_ConsultarCifrasControlResponse_QNAME, ConsultarCifrasControlResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarFacturasCifrasControlResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sei.cifrascontrol.modulointegrador.isban.mx/", name = "consultarFacturasCifrasControlResponse")
    public JAXBElement<ConsultarFacturasCifrasControlResponse> createConsultarFacturasCifrasControlResponse(ConsultarFacturasCifrasControlResponse value) {
        return new JAXBElement<ConsultarFacturasCifrasControlResponse>(_ConsultarFacturasCifrasControlResponse_QNAME, ConsultarFacturasCifrasControlResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarDetalleCifrasControlResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sei.cifrascontrol.modulointegrador.isban.mx/", name = "consultarDetalleCifrasControlResponse")
    public JAXBElement<ConsultarDetalleCifrasControlResponse> createConsultarDetalleCifrasControlResponse(ConsultarDetalleCifrasControlResponse value) {
        return new JAXBElement<ConsultarDetalleCifrasControlResponse>(_ConsultarDetalleCifrasControlResponse_QNAME, ConsultarDetalleCifrasControlResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarCifrasControl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sei.cifrascontrol.modulointegrador.isban.mx/", name = "consultarCifrasControl")
    public JAXBElement<ConsultarCifrasControl> createConsultarCifrasControl(ConsultarCifrasControl value) {
        return new JAXBElement<ConsultarCifrasControl>(_ConsultarCifrasControl_QNAME, ConsultarCifrasControl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarDetalleCifrasControl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sei.cifrascontrol.modulointegrador.isban.mx/", name = "consultarDetalleCifrasControl")
    public JAXBElement<ConsultarDetalleCifrasControl> createConsultarDetalleCifrasControl(ConsultarDetalleCifrasControl value) {
        return new JAXBElement<ConsultarDetalleCifrasControl>(_ConsultarDetalleCifrasControl_QNAME, ConsultarDetalleCifrasControl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarFacturasCifrasControl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sei.cifrascontrol.modulointegrador.isban.mx/", name = "consultarFacturasCifrasControl")
    public JAXBElement<ConsultarFacturasCifrasControl> createConsultarFacturasCifrasControl(ConsultarFacturasCifrasControl value) {
        return new JAXBElement<ConsultarFacturasCifrasControl>(_ConsultarFacturasCifrasControl_QNAME, ConsultarFacturasCifrasControl.class, null, value);
    }

}
